# Generated by Django 5.2.1 on 2025-05-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Pazudis'), (2, 'Atrasts'), (3, 'Redzēts')], verbose_name='Statuss')),
            ],
            options={
                'verbose_name': 'Mājdzīvnieks',
                'verbose_name_plural': 'Mājdzīvnieki',
            },
        ),
    ]
