# Generated by Django 5.2.1 on 2025-06-09 13:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='age',
            field=models.IntegerField(blank=True, choices=[(1, 'Mazulis'), (2, 'Pieaugušais'), (3, 'Seniors')], null=True, verbose_name='Vecums'),
        ),
        migrations.AddField(
            model_name='pet',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='behavior',
            field=models.IntegerField(blank=True, choices=[(1, 'Draudzīgs'), (2, 'Agresīvs'), (3, 'Mierīgs'), (4, 'Bailīgs'), (5, 'Paklausīgs')], null=True, verbose_name='Uzvedība'),
        ),
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sķirne'),
        ),
        migrations.AddField(
            model_name='pet',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Kontakttālrunis'),
        ),
        migrations.AddField(
            model_name='pet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Ziņots'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='event_occurred_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Notikuma laiks'),
        ),
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Tēviņš'), (2, 'Mātīte')], null=True, verbose_name='Dzimums'),
        ),
        migrations.AddField(
            model_name='pet',
            name='identifier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='pet',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Vai ir publisks?'),
        ),
        migrations.AddField(
            model_name='pet',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Vai ir pārbaudīts?'),
        ),
        migrations.AddField(
            model_name='pet',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=24.45, max_digits=9, verbose_name='Ģeogrāfiskais platums'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=56.32, max_digits=9, verbose_name='Ģeogrāfiskais garums'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vārds'),
        ),
        migrations.AddField(
            model_name='pet',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Piezīmes'),
        ),
        migrations.AddField(
            model_name='pet',
            name='pattern',
            field=models.IntegerField(blank=True, choices=[(1, 'Vienkrāsains'), (2, 'Strīpains'), (3, 'Punktveida'), (4, 'Plankumains'), (5, 'Raibs')], null=True, verbose_name='Kažoka raksts'),
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_image_1',
            field=models.URLField(default='https://example.com', max_length=255, verbose_name='Mājdzīvnieka 1. attēls'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_image_2',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Mājdzīvnieka 2. attēls'),
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_image_3',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Mājdzīvnieka 3. attēls'),
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_image_4',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Mājdzīvnieka 4. attēls'),
        ),
        migrations.AddField(
            model_name='pet',
            name='phone_code',
            field=models.IntegerField(blank=True, choices=[(371, 'LV (+371)'), (370, 'LT (+370)'), (372, 'EE (+372)')], null=True, verbose_name='Telefona kods'),
        ),
        migrations.AddField(
            model_name='pet',
            name='primary_color',
            field=models.IntegerField(blank=True, choices=[(1, 'Melns'), (2, 'Pelēks'), (3, 'Balts'), (4, 'Krēmīgs'), (5, 'Dzeltens'), (6, 'Zeltains'), (7, 'Brūns'), (8, 'Sarkans'), (9, 'Lillīgs'), (10, 'Zils'), (11, 'Zaļš'), (12, 'Haki'), (13, 'Bēšīgs'), (14, 'Dzeltenbrūns'), (15, 'Kaštanbrūns')], null=True, verbose_name='Pamatkrāsa'),
        ),
        migrations.AddField(
            model_name='pet',
            name='secondary_color',
            field=models.IntegerField(blank=True, choices=[(1, 'Melns'), (2, 'Pelēks'), (3, 'Balts'), (4, 'Krēmīgs'), (5, 'Dzeltens'), (6, 'Zeltains'), (7, 'Brūns'), (8, 'Sarkans'), (9, 'Lillīgs'), (10, 'Zils'), (11, 'Zaļš'), (12, 'Haki'), (13, 'Bēšīgs'), (14, 'Dzeltenbrūns'), (15, 'Kaštanbrūns')], null=True, verbose_name='Sekundārā krāsa'),
        ),
        migrations.AddField(
            model_name='pet',
            name='size',
            field=models.IntegerField(blank=True, choices=[(1, 'Mazs'), (2, 'Vidējs'), (3, 'Liels')], null=True, verbose_name='Izmērs'),
        ),
        migrations.AddField(
            model_name='pet',
            name='species',
            field=models.IntegerField(choices=[(1, 'Suns'), (2, 'Kaķis'), (3, 'Cits')], default=1, verbose_name='Suga'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PetSightingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Atrasts'), (2, 'Redzēts')], default=2, verbose_name='Statuss')),
                ('event_occurred_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Notikuma laiks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ziņots')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Ģeogrāfiskais platums')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Ģeogrāfiskais garums')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Piezīmes')),
                ('pet_image', models.URLField(max_length=255, verbose_name='Mājdzīvnieka attēls')),
                ('is_public', models.BooleanField(default=True, verbose_name='Vai ir publisks?')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Vai ir pārbaudīts?')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightings_history', to='pets.pet')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ziņotājs')),
            ],
            options={
                'verbose_name': 'Mājdzīvnieka novērojums',
                'verbose_name_plural': 'Mājdzīvnieka novērojumi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFavorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='pets.pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'pet'), name='unique_user_pet')],
            },
        ),
    ]
