# Generated by Django 5.2.1 on 2025-06-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_age_pet_author_pet_behavior_pet_breed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='final_status',
            field=models.IntegerField(choices=[(1, 'Nav atrisināts'), (2, 'Atgriezts saimniekam'), (3, 'Nodots patversmei'), (4, 'Joprojām tiek meklēts'), (5, 'Nav aktuāli'), (6, 'Atradies miris'), (7, 'Saimnieks neatrasts')], default=1, verbose_name='Galīgais statuss'),
        ),
    ]
