# Generated by Django 5.2.1 on 2025-06-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_remove_petsightinghistory_event_occurred_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petsightinghistory',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Ģeogrāfiskais platums'),
        ),
        migrations.AlterField(
            model_name='petsightinghistory',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Ģeogrāfiskais garums'),
        ),
        migrations.AlterField(
            model_name='petsightinghistory',
            name='pet_image',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Mājdzīvnieka attēls'),
        ),
    ]
