# Generated by Django 5.2.1 on 2025-06-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_alter_petsightinghistory_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Ziņojums slēgts'),
        ),
    ]
