# Generated by Django 5.2.1 on 2025-06-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_pet_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='final_status',
            field=models.IntegerField(choices=[(1, 'Nav atrisināts'), (2, 'Atgriezts saimniekam'), (3, 'Nodots patversmei'), (4, 'Paturēts sev'), (5, 'Klaiņojošs'), (6, 'Brīvā pastaigā'), (7, 'Miris'), (8, 'Atradies'), (9, 'Cits')], default=1, verbose_name='Galīgais statuss'),
        ),
    ]
