# Generated by Django 5.2.1 on 2025-06-09 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.PositiveSmallIntegerField(choices=[(1, 'Bug Report'), (2, 'General Questions'), (3, 'Feature Request'), (4, 'Collaboration Request'), (5, 'Other')], default=5, help_text='Select the subject of your feedback')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False, help_text='Mark if feedback has been addressed')),
                ('user', models.ForeignKey(blank=True, help_text='Optional link to registered user', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
