# Generated by Django 5.2.1 on 2025-06-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='shelter',
            name='animal_types',
            field=models.ManyToManyField(blank=True, related_name='shelters', to='shelters.animaltype', verbose_name='Animal types'),
        ),
    ]
