# Generated by Django 5.2.1 on 2025-06-09 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_type', models.IntegerField(choices=[(1, 'Stundā'), (2, 'Vienībā'), (3, 'Dienā'), (4, 'Pēc vienošanās')], default=1)),
                ('category', models.IntegerField(choices=[(1, 'Dzīvnieku pieskatīšana'), (2, 'Suņu pastaigas'), (3, 'Kopšana'), (4, 'Apmācība'), (5, 'Izmitināšana'), (6, 'Veterinārārsts'), (7, 'Foto sesijas'), (8, 'Glābšana un meklēšana'), (9, 'Piederumi un aksesuāri'), (10, 'Māksla'), (11, 'Apbedīšana'), (12, 'Transports'), (13, 'Audzētavas'), (14, 'Apdrošināšana'), (15, 'Citi pakalpojumi')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('provider_type', models.IntegerField(choices=[(1, 'Fiziska persona'), (2, 'Juridiska persona')])),
                ('service_image_1', models.URLField(max_length=255, verbose_name='Servisa 1. attēls')),
                ('service_image_2', models.URLField(blank=True, max_length=255, null=True, verbose_name='Servisa 2. attēls')),
                ('service_image_3', models.URLField(blank=True, max_length=255, null=True, verbose_name='Servisa 3. attēls')),
                ('service_image_4', models.URLField(blank=True, max_length=255, null=True, verbose_name='Servisa 4. attēls')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Vietne')),
                ('is_online', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefona numurs')),
                ('phone_code', models.CharField(blank=True, choices=[(371, 'LV (+371)'), (370, 'LT (+370)'), (372, 'EE (+372)')], max_length=5, null=True, verbose_name='Telefona kods')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-pasts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_title', models.CharField(max_length=100)),
                ('location_description', models.TextField()),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reģions')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pilsēta')),
                ('street', models.CharField(blank=True, max_length=200, null=True, verbose_name='Iela')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Pasta indekss')),
                ('full_address', models.TextField(blank=True, null=True, verbose_name='Adrese')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Ģeogrāfiskais platums')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Ģeogrāfiskais garums')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='services.service')),
            ],
            options={
                'unique_together': {('service', 'user')},
            },
        ),
        migrations.CreateModel(
            name='UserServiceFavorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='services.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'service'), name='unique_user_service')],
            },
        ),
    ]
