# Generated by Django 5.2.1 on 2025-06-18 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='provider_type',
            new_name='provider',
        ),
    ]
