# Generated by Django 5.2.1 on 2025-06-29 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_subscribed',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='subscription_end',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='subscription_start',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='subscription_type',
        ),
    ]
